name: RolePlay
version: 5.5
api: 3.0.0
main: FazrilDev\Main
author: FazrilDev

commands: 
  tugas:
    description: "Take your assignment"
  kantin:
    description: "Let's snack"
  hub:
    description: "Teleport to school"
  claim:
    description: "Claim you awards"